version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloakCon
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - keycloak-volume:/opt/keycloak/data
    command: ["start-dev"]
    
volumes:
  keycloak-volume: